spring:
  profiles:
    active: local
    include: key
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # OAuth2.0
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize  # 네이버 로그인 요청 uri
            token-uri: https://nid.naver.com/oauth2.0/token  # 토큰을 발급받기 위한 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me  # 유저 정보를 받아오기 위한 uri
            user-name-attribute: response  # 회원 정보를 JSON으로 받을 때 키 이름을 response로 지정
        registration:
          naver:
            client-id: ENC(YmiWvZbo4coLHAeamDPKO8c8PR/Y3XRtIjlCcxp2/bM=)
            client-secret: ENC(jv2N6oEwm+ax8wQo/NfuTZIYLwlkuofS)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/auth/callback/naver
            scope:
              - name
              - email

logging:
  level:
    org.hibernate.sql: debug
